### ISSUE TITLE
Race conditions during run

### ISSUE THREAD

**Issue by avnerenv0** [env0/terratag#143]
When running for a large codebase we get
```
fatal error: concurrent map writes
"
"
goroutine 206 [running]:
runtime.throw({0xc71cda?, 0xc5f9f1?})
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/panic.go:992 +0x71 fp=0xc002be37c0 sp=0xc002be3790 pc=0x434111
runtime.mapassign_faststr(0xb86d60, 0xc0003de7e0, {0xc000319120, 0x3})
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/map_faststr.go:295 +0x38b fp=0xc002be3828 sp=0xc002be37c0 pc=0x4132cb
github.com/env0/terratag/internal/tfschema.getClient({0xc000319120, 0x3}, {0xc5f9f1, 0x1})
        /home/runner/work/terratag/terratag/internal/tfschema/tfschema.go:107 +0x14c fp=0xc002be38f8 sp=0xc002be3828 pc=0xaed04c
github.com/env0/terratag/internal/tfschema.IsTaggable({0xc5f9f1, 0x1}, {{0x0, 0xc00087b020}, 0xc00247f2f0, 0xc00247f320, 0xc00247f3e0, 0xc00247f410, 0xc0005c8270, 0xc0005c82a0})
        /home/runner/work/terratag/terratag/internal/tfschema/tfschema.go:28 +0x12f fp=0xc002be3a40 sp=0xc002be38f8 pc=0xaec7ef
github.com/env0/terratag.tagFileResources({0xc000448b40, 0x34}, {0xc5f9f1, 0x1}, {0xc5fa5b, 0x2}, {0x7ffe626058f2, 0x77}, {0x1, 0x1}, ...)
        /home/runner/work/terratag/terratag/terratag.go:139 +0x5dd fp=0xc002be3ee0 sp=0xc002be3a40 pc=0xaee33d
github.com/env0/terratag.tagDirectoryResources.func1({0xc000448b40, 0x34})
        /home/runner/work/terratag/terratag/terratag.go:86 +0x125 fp=0xc002be3fc0 sp=0xc002be3ee0 pc=0xaedac5
github.com/env0/terratag.tagDirectoryResources.func2()
        /home/runner/work/terratag/terratag/terratag.go:93 +0x2e fp=0xc002be3fe0 sp=0xc002be3fc0 pc=0xaed96e
runtime.goexit()
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002be3fe8 sp=0xc002be3fe0 pc=0x463341
created by github.com/env0/terratag.tagDirectoryResources
        /home/runner/work/terratag/terratag/terratag.go:73 +0x32b
```

Also when running `go test -race -run TestTerraform11`
I get
```
--- FAIL: TestTerraform11 (0.21s)
    --- FAIL: TestTerraform11/aws_tags_map_11 (20.37s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/google_labels_map_11 (22.48s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/azurerm_kubernetes_cluster_11 (26.49s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/azurerm_tags_map_11 (25.19s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/aws_tags_merge (39.61s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/aws_submodule (41.24s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/aws_autoscaling_group (42.90s)
        testing.go:1312: race detected during execution of test
    --- FAIL: TestTerraform11/aws_tags_block (44.78s)
        testing.go:1312: race detected during execution of test
```

We need to make sure we remove the race conditions.

**Comment by avnerenv0** [comment]
also getting this in the tests

```
==================
WARNING: DATA RACE
Write at 0x0000027ca6d0 by goroutine 26:
  github.com/env0/terratag.run_terratag()
      /Users/avnersorek/env0/terratag/terratag_test.go:237 +0x1b0
  github.com/env0/terratag.itShouldRunTerratag()
      /Users/avnersorek/env0/terratag/terratag_test.go:152 +0x84
  github.com/env0/terratag.testTerraform.func1()
      /Users/avnersorek/env0/terratag/terratag_test.go:102 +0xa4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47

Previous write at 0x0000027ca6d0 by goroutine 25:
  github.com/env0/terratag.run_terratag()
      /Users/avnersorek/env0/terratag/terratag_test.go:246 +0x5e8
  github.com/env0/terratag.itShouldRunTerratag()
      /Users/avnersorek/env0/terratag/terratag_test.go:152 +0x84
  github.com/env0/terratag.testTerraform.func1()
      /Users/avnersorek/env0/terratag/terratag_test.go:102 +0xa4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1486 +0x724
  github.com/env0/terratag.testTerraform()
      /Users/avnersorek/env0/terratag/terratag_test.go:98 +0x258
  github.com/env0/terratag.TestTerraform11()
      /Users/avnersorek/env0/terratag/terratag_test.go:43 +0x3a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47

Goroutine 25 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1486 +0x724
  github.com/env0/terratag.testTerraform()
      /Users/avnersorek/env0/terratag/terratag_test.go:98 +0x258
  github.com/env0/terratag.TestTerraform11()
      /Users/avnersorek/env0/terratag/terratag_test.go:43 +0x3a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
==================
```
