### ISSUE TITLE
Running terratag throw an error "lstat ../../modules/<deleted_module>: no such file or directory"

### ISSUE THREAD

**Issue by HeverFarber** [env0/terratag#92]
After we delete exists module from TF files, Terratag throws an exception and can't run.

```
InternalServerError - panic: lstat ../../modules/aws-config: no such file or directory

goroutine 1 [running]:
github.com/env0/terratag/errors.PanicOnError(...)
	/home/runner/work/terratag/terratag/errors/errors.go:10
github.com/env0/terratag/terraform.getTerraformModulesDirPaths(0xde8e3d, 0x1, 0xc000402060, 0x2, 0x2)
	/home/runner/work/terratag/terratag/terraform/terraform.go:126 +0x4a6
github.com/env0/terratag/terraform.GetTerraformFilePaths(0xde8e3d, 0x1, 0xc000300701, 0x50, 0x50)
	/home/runner/work/terratag/terratag/terraform/terraform.go:90 +0xe5
main.Terratag(0x7fff8e4c0a06, 0x77, 0xde8e3d, 0x1, 0x0, 0x0, 0x1)
	/home/runner/work/terratag/terratag/main.go:56 +0x94
main.main()
	/home/runner/work/terratag/terratag/main.go:31 +0x10b
```

**Comment by HeverFarber** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Terratag - throw an error when someone will delete module](https://trello.com/c/g74YC11b/3812-terratag-throw-an-error-when-someone-will-delete-module)

**Comment by roni-frantchi** [comment]
We should make Terratag skip any modules that aren't found in modules.json
